######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 23 12:09:54 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += src/algorithm.cpp \
           src/main.cpp
